/* LANDING PAGE */
export const LANDING_PAGE_MOBILE_MENU_TOGGLE = 'LANDING_PAGE_MOBILE_MENU_TOGGLE';
export const LANDING_PAGE_MOBILE_MENU_CLOSE = 'LANDING_PAGE_MOBILE_MENU_CLOSE';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* DASHBOARD */
export const GRAPH_GET_LIST = "GRAPH_GET_LIST";
export const GRAPH_GET_LIST_SUCCESS = "GRAPH_GET_LIST_SUCCESS";
export const HISTOGRAM_GET_LIST = "HISTOGRAM_GET_LIST";
export const HISTOGRAM_GET_LIST_SUCCESS = "HISTOGRAM_GET_LIST_SUCCESS";
export const SALE_GET_LIST = "SALE_GET_LIST";
export const SALE_GET_LIST_SUCCESS = "SALE_GET_LIST_SUCCESS";
export const STOCKTABLE_GET_LIST = "STOCKTABLE_GET_LIST";
export const STOCKTABLE_GET_LIST_SUCCESS = "STOCKTABLE_GET_LIST_SUCCESS";

/* CUSTOMER API */
export const CUSTOMER_GET_LIST = "CUSTOMER_GET_LIST";
export const CUSTOMER_GET_LIST_SUCCESS = "CUSTOMER_GET_LIST_SUCCESS";
export const CUSTOMER_POST_ITEM = "CUSTOMER_POST_ITEM";
export const CUSTOMER_POST_ITEM_SUCCESS = "CUSTOMER_POST_ITEM_SUCCESS";
export const CUSTOMER_POST_CHECK_NAME = "CUSTOMER_POST_CHECK_NAME";
export const CUSTOMER_POST_CHECK_NAME_RESPONSE = "CUSTOMER_POST_CHECK_NAME_RESPONSE";
export const CUSTOMER_SELECTED = "CUSTOMER_SELECTED";

/* FILL API */
export const FILL_GET_LIST = "FILL_GET_LIST";
export const FILL_GET_LIST_SUCCESS = "FILL_GET_LIST_SUCCESS";
export const FILL_POST_ITEM = "FILL_POST_ITEM";
export const FILL_POST_ITEM_SUCCESS = "FILL_POST_ITEM_SUCCESS";

/* FIX COST API */
export const FIXCOST_POST_ITEM = "FIXCOST_POST_ITEM"
export const FIXCOST_POST_ITEM_SUCCESS = "FIXCOST_POST_ITEM_SUCCESS"

/* HISTORY API */
export const HISTORY_GET_LIST = "HISTORY_GET_LIST";
export const HISTORY_GET_LIST_SUCCESS = "HISTORY_GET_LIST_SUCCESS";

/* NOTIFICATION */
export const NOTIFICATION_GET = "NOTIFICATION_GET_LIST";
export const NOTIFICATION_GET_SUCCESS = "NOTIFICATION_GET_LIST_SUCCESS";
export const NOTIFICATION_CHANGE = "NOTIFICATION_CHANGE";

/* ORDER API */
export const ORDER_GET_LIST = "ORDER_GET_LIST";
export const ORDER_GET_LIST_SUCCESS = "ORDER_GET_LIST_SUCCESS";
export const ORDER_POST_ITEM = "ORDER_POST_ITEM";
export const ORDER_POST_ITEM_SUCCESS = "ORDER_POST_ITEM_SUCCESS";
export const ORDER_DELETE_ITEM = "ORDER_DELETE_ITEM";

/* PAYMENT */
export const PACKAGE_GET_LIST = "PACKAGE_GET_LIST";
export const PACKAGE_GET_LIST_SUCCESS = "PACKAGE_GET_LIST_SUCCESS";
export const PACKAGE_SELECTEDE = "PACKAGE_SELECTEDE" ;
export const PACKAGE_CONFIRM = "PACKAGE_CONFIRM";
export const PACKAGE_CONFIRM_SUCCESS = "PACKAGE_CONFIRM_SUCCESS";
export const PAYMENT_GET_LIST = "PAYMENT_GET_LIST";
export const PAYMENT_GET_LIST_SUCCESS = "PAYMENT_GET_LIST_SUCCESS";
export const PAYMENT_CONFIRM = "PAYMENT_CONFIRM";
export const PAYMENT_CONFIRM_SUCCESS = "PAYMENT_CONFIRM_SUCCESS";
export const PAYMENT_CANCLE_ITEM = "PAYMENT_CANCLE_ITEM";
export const PAYMENT_GET_LIST_BY_STAFF = "PAYMENT_GET_LIST_BY_STAFF"
export const PAYMENT_GET_LIST_BY_STAFF_SUCCESS = "PAYMENT_GET_LIST_BY_STAFF_SUCCESS";
export const PAYMENT_APPROVE_ITEM = "PAYMENT_APPROVE_ITEM";

/* PRIVATE PRICE */
export const PRIVATE_PRICE_GET_LIST = "PRIVATE_PRICE_GET_LIST";
export const PRIVATE_PRICE_GET_LIST_SUCCESS = "PRIVATE_PRICE_GET_LIST_SUCCESS";
export const PRIVATE_PRICE_POST_ITEM = "PRIVATE_PRICE_POST_ITEM";

/* PROMOTION */
export const PROMOTION_GET_LIST = "PROMOTION_GET_LIST";
export const PROMOTION_GET_LIST_SUCCESS = "PROMOTION_GET_LIST_SUCCESS";
export const PROMOTION_POST_ITEM = "PROMOTION_POST_ITEM";
export const PROMOTION_HISTORY_GET_LIST = "PROMOTION_HISTORY_GET_LIST";
export const PROMOTION_HISTORY_GET_LIST_SUCCESS = "PROMOTION_HISTORY_GET_LIST_SUCCESS";

/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* STOCK API */
export const STOCK_GET_LIST = "STOCK_GET_LIST";
export const STOCK_GET_LIST_SUCCESS = "STOCK_GET_LIST_SUCCESS";
export const STOCK_POST_ITEM = "STOCK_POST_ITEM";
export const STOCK_POST_ITEM_SUCCESS = "STOCK_POST_ITEM_SUCCESS";

/* USER API */
export const USER_GET_LIST = "USER_GET_LIST";
export const USER_GET_LIST_SUCCESS = "USER_GET_LIST_SUCCESS";

/*  VENDOR API */
export const VENDOR_GET_LIST = "VENDOR_GET_LIST";
export const VENDOR_GET_LIST_SUCCESS = "VENDOR_GET_LIST_SUCCESS";

/* ADMIN API */
export const ADMIN_VENDOR_GET_LIST = "ADMIN_VENDOR_GET_LIST";
export const ADMIN_VENDOR_GET_LIST_SUCCESS = "ADMIN_VENDOR_GET_LIST_SUCCESS";
export const ADMIN_REGISTER_APPROVE_ITEM = "ADMIN_REGISTER_APPROVE_ITEM";
